# Generated by Django 3.1.7 on 2021-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210403_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlines',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
