# Generated by Django 3.1.7 on 2021-04-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_headlines_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlines',
            name='image',
        ),
        migrations.RemoveField(
            model_name='headlines',
            name='publish_date',
        ),
    ]
